# Generated by Django 5.2.4 on 2025-09-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_email_profile_github_profile_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
