# Generated by Django 5.2.4 on 2025-09-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_superuser'),
        ('home', '0007_profile_profile_image_url_profile_resume_url_and_more'),
    ]

    operations = [
    ]
